---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot-sriov-1
  namespace: default
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
    resources:
     claims:
       - name: sriov-vf-leaf-101-102-service-1
  resourceClaims:
  - name: sriov-vf-leaf-101-102-service-1
    resourceClaimTemplateName: sriov-service-1