---
apiVersion: cilium.io/v2alpha1
kind: CiliumResourceIPPool
metadata:
  name: ip-pool-leaf-101
spec:
  ipv4:
    cidrs:
      - 10.10.1.0/24
    maskSize: 24
  ipv6:
    cidrs:
      - 2001:db8::/64
    maskSize: 64
---
apiVersion: cilium.io/v2alpha1
kind: CiliumResourceIPPool
metadata:
  name: ip-pool-leaf-102
spec:
  ipv4:
    cidrs:
      - 10.10.2.0/24
    maskSize: 24
  ipv6:
    cidrs:
      - 2001:db9::/64
    maskSize: 64