---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: sriov-service-1
  namespace: default
spec:
  spec:
    devices:
      config:
        - requests:
            - leaf-101
          opaque:
            driver: sriov.cilium.k8s.io
            parameters:
              vlan: 3041
              ipv4Addr: 10.10.1.10/24
        - requests:
            - leaf-102
          opaque:
            driver: sriov.cilium.k8s.io
            parameters:
              vlan: 3042
              ipv4Addr: 10.10.2.10/24
      requests:
      - name: leaf-101
        exactly:
          deviceClassName: leaf-101.sriov.cilium.k8s.io
      - name: leaf-102
        exactly:
          deviceClassName: leaf-102.sriov.cilium.k8s.io