---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot-sriov-1
  namespace: default
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
    volumeMounts:
    - mountPath: /tmp/pcap
      name: pcap
      readOnly: true
  resourceClaims:
  - name: demo-claim
    resourceClaimTemplateName: sriov-demo-service
  volumes:
  - name: pcap
    hostPath:
      path: /home/cisco/pcap
      type: Directory
