apiVersion: cilium.io/v2alpha1
kind: CiliumResourceIPPool
metadata:
  name: service-1a-ip-pool
spec:
  ipv4:
    cidrs:
    - 10.10.1.0/24
    maskSize: 24
---
apiVersion: cilium.io/v2alpha1
kind: CiliumResourceIPPool
metadata:
  name: service-1b-ip-pool
spec:
  ipv4:
    cidrs:
    - 10.10.2.0/24
    maskSize: 24