apiVersion: cilium.io/v2alpha1
kind: CiliumResourceIPPool
metadata:
  name: service-2a-ip-pool
spec:
  ipv4:
    cidrs:
    - 10.10.3.0/24
    maskSize: 24
---
apiVersion: cilium.io/v2alpha1
kind: CiliumResourceIPPool
metadata:
  name: service-2b-ip-pool
spec:
  ipv4:
    cidrs:
    - 10.10.4.0/24
    maskSize: 24