---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot-sriov-2
  namespace: default
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
  resourceClaims:
  - name: service-2-claim
    resourceClaimTemplateName: service-2