---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: service-1
  namespace: default
spec:
  spec:
    devices:
      config:
        - requests:
            - leaf-101
          opaque:
            driver: sriov.cilium.k8s.io
            parameters:
              vlan: 3041
              networkConfig: service-1a-network-config
        - requests:
            - leaf-102
          opaque:
            driver: sriov.cilium.k8s.io
            parameters:
              vlan: 3042
              networkConfig: service-1b-network-config
      requests:
      - name: leaf-101
        exactly:
          deviceClassName: leaf-101.sriov.cilium.k8s.io
      - name: leaf-102
        exactly:
          deviceClassName: leaf-102.sriov.cilium.k8s.io